//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CakesEntities : DbContext
    {
        public CakesEntities()
            : base("name=CakesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Изделие> Изделие { get; set; }
        public virtual DbSet<Ингредиенты> Ингредиенты { get; set; }
        public virtual DbSet<Инструменты> Инструменты { get; set; }
        public virtual DbSet<Оборудование> Оборудование { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Поставщик> Поставщик { get; set; }
        public virtual DbSet<Спецификация_ингредиенты> Спецификация_ингредиенты { get; set; }
        public virtual DbSet<Спецификация_операции> Спецификация_операции { get; set; }
        public virtual DbSet<Спецификация_полуфабрикат> Спецификация_полуфабрикат { get; set; }
        public virtual DbSet<Спецификация_украшения_для_торта> Спецификация_украшения_для_торта { get; set; }
        public virtual DbSet<Тип_оборудования> Тип_оборудования { get; set; }
        public virtual DbSet<Украшения_для_торта> Украшения_для_торта { get; set; }
    }
}
