//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Инструменты
    {
        public int ID_Инструмента { get; set; }
        public string Наименование { get; set; }
        public string Описание { get; set; }
        public string Тип_инструмента { get; set; }
        public string Степень_износа { get; set; }
        public string Поставщик { get; set; }
        public Nullable<System.DateTime> Дата_покупки { get; set; }
        public Nullable<int> Количество { get; set; }
    }
}
