//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ингредиенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ингредиенты()
        {
            this.Спецификация_ингредиенты = new HashSet<Спецификация_ингредиенты>();
        }
    
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Единицы_измерения { get; set; }
        public int Количество { get; set; }
        public string Тип { get; set; }
        public decimal Цена { get; set; }
        public string ГОСТ { get; set; }
        public string Фасовка { get; set; }
        public string Характеристика { get; set; }
        public string Поставщик { get; set; }
        public string Изображение { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
    
        public virtual Поставщик Поставщик1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Спецификация_ингредиенты> Спецификация_ингредиенты { get; set; }
    }
}
