//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Спецификация_операции
    {
        public string Изделие { get; set; }
        public string Операция { get; set; }
        public int Порядковый_номер { get; set; }
        public string Тип_оборудования { get; set; }
        public System.TimeSpan Время_на_операцию { get; set; }
    
        public virtual Изделие Изделие1 { get; set; }
        public virtual Тип_оборудования Тип_оборудования1 { get; set; }
    }
}
