//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Украшения_для_торта
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Украшения_для_торта()
        {
            this.Спецификация_украшения_для_торта = new HashSet<Спецификация_украшения_для_торта>();
        }
    
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Единицы_измерения { get; set; }
        public int Количество { get; set; }
        public string Тип { get; set; }
        public decimal Закуп_Цена { get; set; }
        public double Вес { get; set; }
        public string Поставщик { get; set; }
        public string Изображение { get; set; }
    
        public virtual Поставщик Поставщик1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Спецификация_украшения_для_торта> Спецификация_украшения_для_торта { get; set; }
    }
}
